import type { Issue, Sprint, Priority, IssueStatus } from "@/types"

// Priority color mapping
export const priorityColors: Record<Priority, string> = {
  P0: "bg-red-500 text-white",
  P1: "bg-orange-500 text-white",
  P2: "bg-yellow-500 text-black",
  P3: "bg-blue-500 text-white",
  P4: "bg-green-500 text-white",
  P5: "bg-gray-500 text-white",
}

// Status color mapping
export const statusColors: Record<IssueStatus, string> = {
  Todo: "bg-gray-100 text-gray-800 border-gray-200",
  "In Progress": "bg-blue-100 text-blue-800 border-blue-200",
  "In Review": "bg-yellow-100 text-yellow-800 border-yellow-200",
  Done: "bg-green-100 text-green-800 border-green-200",
}

// Generate auto-incrementing task ID
export const generateTaskId = (existingIssues: Issue[]): string => {
  const maxId = existingIssues.reduce((max, issue) => {
    const num = Number.parseInt(issue.id.replace("TSK-", ""))
    return num > max ? num : max
  }, 0)
  return `TSK-${String(maxId + 1).padStart(3, "0")}`
}

// Helper function to get the Monday of the current week
const getMondayOfWeek = (date: Date): Date => {
  const d = new Date(date)
  const day = d.getDay()
  const diff = d.getDate() - day + (day === 0 ? -6 : 1) // Adjust when day is Sunday
  return new Date(d.setDate(diff))
}

// Helper function to get the start of a two-week sprint period
const getSprintStartDate = (weeksFromNow: number): Date => {
  const today = new Date()
  const currentMonday = getMondayOfWeek(today)
  const sprintStart = new Date(currentMonday)
  sprintStart.setDate(sprintStart.getDate() + (weeksFromNow * 7))
  return sprintStart
}

// Helper function to get the end of a two-week sprint period
const getSprintEndDate = (startDate: Date): Date => {
  const endDate = new Date(startDate)
  endDate.setDate(endDate.getDate() + 13) // 14 days total (start + 13 days)
  return endDate
}

// Sample data with two-week sprints starting on Mondays in 2025
export const initialSprints: Sprint[] = [
  {
    id: "sprint-1",
    name: "Sprint 1 - Foundation",
    status: "Completed",
    startDate: new Date("2025-01-06"), // Jan 6-19, 2025
    endDate: new Date("2025-01-19"),
    createdAt: new Date("2025-01-06"),
    updatedAt: new Date("2025-01-19"),
  },
  {
    id: "sprint-2",
    name: "Sprint 2 - Core Features",
    status: "Active",
    startDate: new Date("2025-01-20"), // Jan 20 - Feb 2, 2025
    endDate: new Date("2025-02-02"),
    createdAt: new Date("2025-01-20"),
    updatedAt: new Date(),
  },
  {
    id: "sprint-3",
    name: "Sprint 3 - Polish & Testing",
    status: "Planned",
    startDate: new Date("2025-02-03"), // Feb 3-16, 2025
    endDate: new Date("2025-02-16"),
    createdAt: new Date("2025-02-03"),
    updatedAt: new Date(),
  },
  {
    id: "sprint-4",
    name: "Sprint 4 - Performance & Optimization",
    status: "Planned",
    startDate: new Date("2025-02-17"), // Feb 17 - Mar 2, 2025
    endDate: new Date("2025-03-02"),
    createdAt: new Date("2025-02-17"),
    updatedAt: new Date(),
  },
  {
    id: "sprint-5",
    name: "Sprint 5 - Advanced Features",
    status: "Planned",
    startDate: new Date("2025-03-03"), // Mar 3-16, 2025
    endDate: new Date("2025-03-16"),
    createdAt: new Date("2025-03-03"),
    updatedAt: new Date(),
  },
  {
    id: "sprint-6",
    name: "Sprint 6 - Integration & APIs",
    status: "Planned",
    startDate: new Date("2025-03-17"), // Mar 17-30, 2025
    endDate: new Date("2025-03-30"),
    createdAt: new Date("2025-03-17"),
    updatedAt: new Date(),
  },
  {
    id: "sprint-7",
    name: "Sprint 7 - Mobile & Responsive",
    status: "Planned",
    startDate: new Date("2025-03-31"), // Mar 31 - Apr 13, 2025
    endDate: new Date("2025-04-13"),
    createdAt: new Date("2025-03-31"),
    updatedAt: new Date(),
  },
  {
    id: "sprint-8",
    name: "Sprint 8 - Final Polish & Launch",
    status: "Planned",
    startDate: new Date("2025-04-14"), // Apr 14-27, 2025
    endDate: new Date("2025-04-27"),
    createdAt: new Date("2025-04-14"),
    updatedAt: new Date(),
  },
]

export const initialIssues: Issue[] = [
  // Sprint 1 - Foundation (Completed) - Jan 6-19, 2025
  {
    id: "TSK-001",
    title: "Setup project structure",
    description: "Initialize the project with proper folder structure and dependencies",
    priority: "P1",
    status: "Done",
    assignee: "Alice Johnson",
    sprintId: "sprint-1",
    startDate: new Date("2025-01-08"),
    deliveryDate: new Date("2025-01-15"),
    createdAt: new Date("2025-01-08"),
    updatedAt: new Date("2025-01-15"),
    type: "Task",
    progress: 100,
    team: "Frontend",
    labels: ["setup", "infrastructure"],
  },
  {
    id: "TSK-002",
    title: "Design system components",
    description: "Create reusable UI components following design system",
    priority: "P2",
    status: "Done",
    assignee: "Bob Smith",
    sprintId: "sprint-1",
    startDate: new Date("2025-01-09"),
    deliveryDate: new Date("2025-01-16"),
    createdAt: new Date("2025-01-09"),
    updatedAt: new Date("2025-01-16"),
  },
  {
    id: "TSK-003",
    title: "Database schema design",
    description: "Design and implement the database schema for the application",
    priority: "P1",
    status: "Done",
    assignee: "Charlie Brown",
    sprintId: "sprint-1",
    startDate: new Date("2025-01-10"),
    deliveryDate: new Date("2025-01-17"),
    createdAt: new Date("2025-01-10"),
    updatedAt: new Date("2025-01-17"),
  },
  {
    id: "TSK-004",
    title: "User authentication system",
    description: "Implement login, registration, and session management",
    priority: "P0",
    status: "Done",
    assignee: "Alice Johnson",
    sprintId: "sprint-1",
    startDate: new Date("2025-01-11"),
    deliveryDate: new Date("2025-01-18"),
    createdAt: new Date("2025-01-11"),
    updatedAt: new Date("2025-01-18"),
    type: "Epic",
    progress: 100,
    team: "Backend",
    labels: ["authentication", "security"],
  },

  // Sprint 2 - Core Features (Active) - Jan 20 - Feb 2, 2025
  {
    id: "TSK-005",
    title: "Dashboard layout",
    description: "Create the main dashboard with navigation and layout components",
    priority: "P1",
    status: "In Progress",
    assignee: "Bob Smith",
    sprintId: "sprint-2",
    startDate: new Date("2025-01-20"),
    deliveryDate: new Date("2025-01-27"),
    createdAt: new Date("2025-01-20"),
    updatedAt: new Date("2025-01-25"),
    type: "Story",
    progress: 75,
    team: "Frontend",
    labels: ["dashboard", "ui"],
  },
  {
    id: "TSK-006",
    title: "API endpoints for tasks",
    description: "Develop REST API endpoints for CRUD operations on tasks",
    priority: "P1",
    status: "In Progress",
    assignee: "Charlie Brown",
    sprintId: "sprint-2",
    startDate: new Date("2025-01-21"),
    deliveryDate: new Date("2025-01-28"),
    createdAt: new Date("2025-01-21"),
    updatedAt: new Date("2025-01-25"),
    type: "Task",
    progress: 60,
    team: "Backend",
    labels: ["api", "backend"],
  },
  {
    id: "TSK-007",
    title: "Real-time notifications",
    description: "Implement WebSocket-based real-time notifications",
    priority: "P2",
    status: "Todo",
    assignee: "Diana Prince",
    sprintId: "sprint-2",
    startDate: new Date("2025-01-22"),
    deliveryDate: new Date("2025-01-29"),
    createdAt: new Date("2025-01-22"),
    updatedAt: new Date("2025-01-22"),
  },
  {
    id: "TSK-008",
    title: "User profile management",
    description: "Create user profile pages with avatar upload and settings",
    priority: "P1",
    status: "In Progress",
    assignee: "Alice Johnson",
    sprintId: "sprint-2",
    startDate: new Date("2025-01-23"),
    deliveryDate: new Date("2025-01-30"),
    createdAt: new Date("2025-01-23"),
    updatedAt: new Date("2025-01-25"),
  },

  // Sprint 3 - Polish & Testing (Planned) - Feb 3-16, 2025
  {
    id: "TSK-009",
    title: "Task comments system",
    description: "Add commenting functionality to tasks for team collaboration",
    priority: "P2",
    status: "Todo",
    assignee: "Bob Smith",
    sprintId: "sprint-3",
    startDate: new Date("2025-02-03"),
    deliveryDate: new Date("2025-02-10"),
    createdAt: new Date("2025-02-03"),
    updatedAt: new Date("2025-02-03"),
  },
  {
    id: "TSK-010",
    title: "Sprint planning interface",
    description: "Build interface for planning and managing sprints",
    priority: "P0",
    status: "Todo",
    assignee: "Charlie Brown",
    sprintId: "sprint-3",
    startDate: new Date("2025-02-04"),
    deliveryDate: new Date("2025-02-11"),
    createdAt: new Date("2025-02-04"),
    updatedAt: new Date("2025-02-04"),
  },
  {
    id: "TSK-011",
    title: "Drag and drop task reordering",
    description: "Implement drag and drop functionality for task prioritization",
    priority: "P2",
    status: "Todo",
    assignee: "Diana Prince",
    sprintId: "sprint-3",
    startDate: new Date("2025-02-05"),
    deliveryDate: new Date("2025-02-12"),
    createdAt: new Date("2025-02-05"),
    updatedAt: new Date("2025-02-05"),
  },
  {
    id: "TSK-012",
    title: "Task templates",
    description: "Create reusable task templates for common workflows",
    priority: "P3",
    status: "Todo",
    assignee: "Alice Johnson",
    sprintId: "sprint-3",
    startDate: new Date("2025-02-06"),
    deliveryDate: new Date("2025-02-13"),
    createdAt: new Date("2025-02-06"),
    updatedAt: new Date("2025-02-06"),
  },

  // Sprint 4 - Performance & Optimization (Planned) - Feb 17 - Mar 2, 2025
  {
    id: "TSK-013",
    title: "Bulk task operations",
    description: "Enable bulk editing, moving, and deleting of tasks",
    priority: "P2",
    status: "Todo",
    assignee: "Bob Smith",
    sprintId: "sprint-4",
    startDate: new Date("2025-02-17"),
    deliveryDate: new Date("2025-02-24"),
    createdAt: new Date("2025-02-17"),
    updatedAt: new Date("2025-02-17"),
  },
  {
    id: "TSK-014",
    title: "Task dependencies",
    description: "Add support for task dependencies and blocking relationships",
    priority: "P1",
    status: "Todo",
    assignee: "Charlie Brown",
    sprintId: "sprint-4",
    startDate: new Date("2025-02-18"),
    deliveryDate: new Date("2025-02-25"),
    createdAt: new Date("2025-02-18"),
    updatedAt: new Date("2025-02-18"),
  },
  {
    id: "TSK-015",
    title: "Advanced filtering",
    description: "Implement advanced filtering options for tasks and sprints",
    priority: "P2",
    status: "Todo",
    assignee: "Diana Prince",
    sprintId: "sprint-4",
    startDate: new Date("2025-02-19"),
    deliveryDate: new Date("2025-02-26"),
    createdAt: new Date("2025-02-19"),
    updatedAt: new Date("2025-02-19"),
  },
  {
    id: "TSK-016",
    title: "Task time estimation",
    description: "Add time estimation fields and tracking to tasks",
    priority: "P3",
    status: "Todo",
    assignee: "Alice Johnson",
    sprintId: "sprint-4",
    startDate: new Date("2025-02-20"),
    deliveryDate: new Date("2025-02-27"),
    createdAt: new Date("2025-02-20"),
    updatedAt: new Date("2025-02-20"),
  },

  // Sprint 5 - Advanced Features (Planned) - Mar 3-16, 2025
  {
    id: "TSK-017",
    title: "Sprint retrospective",
    description: "Create retrospective interface for sprint reviews",
    priority: "P2",
    status: "Todo",
    assignee: "Bob Smith",
    sprintId: "sprint-5",
    startDate: new Date("2025-03-03"),
    deliveryDate: new Date("2025-03-10"),
    createdAt: new Date("2025-03-03"),
    updatedAt: new Date("2025-03-03"),
  },
  {
    id: "TSK-018",
    title: "Task automation rules",
    description: "Implement automation rules for task status changes",
    priority: "P3",
    status: "Todo",
    assignee: "Charlie Brown",
    sprintId: "sprint-5",
    startDate: new Date("2025-03-04"),
    deliveryDate: new Date("2025-03-11"),
    createdAt: new Date("2025-03-04"),
    updatedAt: new Date("2025-03-04"),
  },
  {
    id: "TSK-019",
    title: "Team collaboration features",
    description: "Add @mentions, notifications, and team communication tools",
    priority: "P1",
    status: "Todo",
    assignee: "Diana Prince",
    sprintId: "sprint-5",
    startDate: new Date("2025-03-05"),
    deliveryDate: new Date("2025-03-12"),
    createdAt: new Date("2025-03-05"),
    updatedAt: new Date("2025-03-05"),
  },
  {
    id: "TSK-020",
    title: "Sprint burndown charts",
    description: "Create visual burndown charts for sprint progress tracking",
    priority: "P2",
    status: "Todo",
    assignee: "Alice Johnson",
    sprintId: "sprint-5",
    startDate: new Date("2025-03-06"),
    deliveryDate: new Date("2025-03-13"),
    createdAt: new Date("2025-03-06"),
    updatedAt: new Date("2025-03-06"),
  },

  // Sprint 6 - Integration & APIs (Planned) - Mar 17-30, 2025
  {
    id: "TSK-021",
    title: "Performance optimization",
    description: "Optimize application performance and loading times",
    priority: "P2",
    status: "Todo",
    assignee: "Alice Johnson",
    sprintId: "sprint-6",
    startDate: new Date("2025-03-17"),
    deliveryDate: new Date("2025-03-24"),
    createdAt: new Date("2025-03-17"),
    updatedAt: new Date("2025-03-17"),
  },
  {
    id: "TSK-022",
    title: "Unit test coverage",
    description: "Write comprehensive unit tests for all components",
    priority: "P3",
    status: "Todo",
    assignee: "Bob Smith",
    sprintId: "sprint-6",
    startDate: new Date("2025-03-18"),
    deliveryDate: new Date("2025-03-25"),
    createdAt: new Date("2025-03-18"),
    updatedAt: new Date("2025-03-18"),
  },
  {
    id: "TSK-023",
    title: "Mobile responsive design",
    description: "Ensure the application works well on mobile devices",
    priority: "P2",
    status: "Todo",
    assignee: "Charlie Brown",
    sprintId: "sprint-6",
    startDate: new Date("2025-03-19"),
    deliveryDate: new Date("2025-03-26"),
    createdAt: new Date("2025-03-19"),
    updatedAt: new Date("2025-03-19"),
  },
  {
    id: "TSK-024",
    title: "Dark mode support",
    description: "Add dark mode theme support throughout the application",
    priority: "P3",
    status: "Todo",
    assignee: "Diana Prince",
    sprintId: "sprint-6",
    startDate: new Date("2025-03-20"),
    deliveryDate: new Date("2025-03-27"),
    createdAt: new Date("2025-03-20"),
    updatedAt: new Date("2025-03-20"),
  },

  // Sprint 7 - Mobile & Responsive (Planned) - Mar 31 - Apr 13, 2025
  {
    id: "TSK-025",
    title: "Export functionality",
    description: "Allow users to export their data in various formats",
    priority: "P4",
    status: "Todo",
    assignee: "Alice Johnson",
    sprintId: "sprint-7",
    startDate: new Date("2025-03-31"),
    deliveryDate: new Date("2025-04-07"),
    createdAt: new Date("2025-03-31"),
    updatedAt: new Date("2025-03-31"),
  },
  {
    id: "TSK-026",
    title: "Advanced search filters",
    description: "Implement advanced filtering and search capabilities",
    priority: "P3",
    status: "Todo",
    assignee: "Bob Smith",
    sprintId: "sprint-7",
    startDate: new Date("2025-04-01"),
    deliveryDate: new Date("2025-04-08"),
    createdAt: new Date("2025-04-01"),
    updatedAt: new Date("2025-04-01"),
  },
  {
    id: "TSK-027",
    title: "Integration with external tools",
    description: "Add integrations with popular project management tools",
    priority: "P4",
    status: "Todo",
    assignee: "Charlie Brown",
    sprintId: "sprint-7",
    startDate: new Date("2025-04-02"),
    deliveryDate: new Date("2025-04-09"),
    createdAt: new Date("2025-04-02"),
    updatedAt: new Date("2025-04-02"),
  },
  {
    id: "TSK-028",
    title: "User onboarding flow",
    description: "Create guided onboarding experience for new users",
    priority: "P2",
    status: "Todo",
    assignee: "Diana Prince",
    sprintId: "sprint-7",
    startDate: new Date("2025-04-03"),
    deliveryDate: new Date("2025-04-10"),
    createdAt: new Date("2025-04-03"),
    updatedAt: new Date("2025-04-03"),
  },

  // Sprint 8 - Final Polish & Launch (Planned) - Apr 14-27, 2025
  {
    id: "TSK-029",
    title: "Analytics dashboard",
    description: "Build analytics dashboard with project insights and metrics",
    priority: "P5",
    status: "Todo",
    assignee: "Alice Johnson",
    sprintId: "sprint-8",
    startDate: new Date("2025-04-14"),
    deliveryDate: new Date("2025-04-21"),
    createdAt: new Date("2025-04-14"),
    updatedAt: new Date("2025-04-14"),
  },
  {
    id: "TSK-030",
    title: "Email notification system",
    description: "Send email notifications for important task updates and deadlines",
    priority: "P3",
    status: "Todo",
    assignee: "Bob Smith",
    sprintId: "sprint-8",
    startDate: new Date("2025-04-15"),
    deliveryDate: new Date("2025-04-22"),
    createdAt: new Date("2025-04-15"),
    updatedAt: new Date("2025-04-15"),
  },
  {
    id: "TSK-031",
    title: "File attachment support",
    description: "Allow users to attach files and documents to tasks",
    priority: "P4",
    status: "Todo",
    assignee: "Charlie Brown",
    sprintId: "sprint-8",
    startDate: new Date("2025-04-16"),
    deliveryDate: new Date("2025-04-23"),
    createdAt: new Date("2025-04-16"),
    updatedAt: new Date("2025-04-16"),
  },
  {
    id: "TSK-032",
    title: "Time tracking functionality",
    description: "Add time tracking capabilities for tasks and sprints",
    priority: "P3",
    status: "Todo",
    assignee: "Diana Prince",
    sprintId: "sprint-8",
    startDate: new Date("2025-04-17"),
    deliveryDate: new Date("2025-04-24"),
    createdAt: new Date("2025-04-17"),
    updatedAt: new Date("2025-04-17"),
  },

  // Backlog issues (no sprint assigned yet)
  {
    id: "TSK-033",
    title: "Custom field support",
    description: "Allow users to create custom fields for tasks",
    priority: "P5",
    status: "Todo",
    assignee: "Alice Johnson",
    startDate: new Date("2025-05-01"),
    deliveryDate: new Date("2025-05-08"),
    createdAt: new Date("2025-05-01"),
    updatedAt: new Date("2025-05-01"),
  },
]
